{% set name = "hdmedians" %}
{% set version = "0.14.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b47aecb16771e1ba0736557255d80ae0240b09156bff434321de559b359ac2d6

build:
  number: 1
  skip: true  # [win]
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv '

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython >=0.23
    - numpy
    - pip
    - python
    - nose
  run:
    - cython >=0.23
    - {{ pin_compatible('numpy') }}
    - python
test:
  imports:
    - hdmedians

about:
  home: http://github.com/daleroberts/hdmedians
  license: Apache-2.0
  license_family: Apache
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: High-dimensional medians

extra:
  recipe-maintainers:
    - ElDeveloper
