{% set name = "hdmedians" %}
{% set version = "0.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 766eb7281b68cd1032b0d3addc4113abf4d63c249261914883f8304db7d29750

build:
  number: 0
  skip: true  # [win]
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv '

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython >=0.23
    - numpy
    - pip
    - python
    - nose
  run:
    - cython >=0.23
    - {{ pin_compatible('numpy') }}
    - python
test:
  imports:
    - hdmedians

about:
  home: http://github.com/daleroberts/hdmedians
  license: GPL3
  license_family: GPL3
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: High-dimensional medians

extra:
  recipe-maintainers:
    - ElDeveloper
