{% set name = "hdmedians" %}
{% set version = "0.14.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ccefaae26302afd843c941b3b662f1119d5a36dec118077310f811a7a1ed8871

build:
  number: 0
  skip: true  # [win]
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv '

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython >=0.23
    - numpy
    - pip
    - python
    - nose
  run:
    - cython >=0.23
    - {{ pin_compatible('numpy') }}
    - python
test:
  imports:
    - hdmedians

about:
  home: http://github.com/daleroberts/hdmedians
  license: Apache-2.0
  license_family: Apache
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: High-dimensional medians

extra:
  recipe-maintainers:
    - ElDeveloper
