travis:
  secure:
    BINSTAR_TOKEN: we/FV4rSzV6JxWzEuYzGF2MdXWwvJ5D6oq7D9x+62OYYFU95ljO2P6VJ4HNpH5KLLXzvc2rx3RmGw+JxspCnQ1GAI2TDmVeRj12cY0l1LAOjC0w3T+N5QRFs3j1bMIidCfDo6ZXYZDvospcU2DuIVwoxniy2oZ2jROJnMAP8/hb0A4WzjwgyzYi2oYF/6eDW4L9D8Ttmom2p58DUrDOfzSBQ3NCGmDbwnkYnbngUGQxF/OufvlcsD3n97uuiPpGtzW2KXcsFDc2MEKGiJ0fTan22Zwi72+aLWsljua+BavG2m+wDQXOWL4XVMxZO3dNATzanqQ9VXzLjRDkLLqkQWTwhIkmLxmQk/omo7OZE93yAVVoarK+VbazP6/QTaEKFShQ+i9SkmwwoDI5eU0Bs0yaVeLv6IhIAnjWmaRIeiztbfd1uIfKovfWtTq4nLdoj1U9Jcxmb/eGAaDGuq5xvbtpXq+VdjbQrzgqF5T8Z/u0EXhuOebz6EWFgt54CYGNfJ+ZTrQ9bzmmP1VXzWR5zk0XN0oC1gDBvst0inw61mXFYVj/4V/cOHC/TS0hgm/7lYl33FklnKDZEj2EOtPLgPU+nxk9I7eJu9J9o42egB/DZzHkhpa2CkvGuaw6BHeRZvN57fENUnFmP/xZcGvENI3f2iiiDvL3xDhAhxrdBCCg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
max_py_ver: '37'
conda_forge_output_validation: true
